//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvengersUtd.Odyssey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvengersUtd.Odyssey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Enum value not valid..
        /// </summary>
        internal static string ERR_EnumNotValid {
            get {
                return ResourceManager.GetString("ERR_EnumNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error..
        /// </summary>
        internal static string ERR_Fatal {
            get {
                return ResourceManager.GetString("ERR_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet supported in the Odyssey Engine..
        /// </summary>
        internal static string ERR_FeatureNotSupported {
            get {
                return ResourceManager.GetString("ERR_FeatureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Filename not valid..
        /// </summary>
        internal static string ERR_FilenameNotValid {
            get {
                return ResourceManager.GetString("ERR_FilenameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only add one RenderableNode to a FreeTransformNode.
        /// </summary>
        internal static string ERR_FtNodeRequiresRNode {
            get {
                return ResourceManager.GetString("ERR_FtNodeRequiresRNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Variable not found in effect file..
        /// </summary>
        internal static string ERR_FXVarNotFound {
            get {
                return ResourceManager.GetString("ERR_FXVarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized material parameter..
        /// </summary>
        internal static string ERR_MaterialParameter {
            get {
                return ResourceManager.GetString("ERR_MaterialParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hardware device does not support shaders version 2.0!.
        /// </summary>
        internal static string ERR_ShaderModelNotSupported {
            get {
                return ResourceManager.GetString("ERR_ShaderModelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter is not applicable to spotlights..
        /// </summary>
        internal static string ERR_SpotlightParameter {
            get {
                return ResourceManager.GetString("ERR_SpotlightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized parameter..
        /// </summary>
        internal static string ERR_UnrecognizedParameter {
            get {
                return ResourceManager.GetString("ERR_UnrecognizedParameter", resourceCulture);
            }
        }
    }
}
