//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvengersUtd.Odyssey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvengersUtd.Odyssey.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command type specified. Use AddRenderCommand() instead..
        /// </summary>
        internal static string ERR_AddBaseCommand {
            get {
                return ResourceManager.GetString("ERR_AddBaseCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add null controls..
        /// </summary>
        internal static string ERR_AddNullControl {
            get {
                return ResourceManager.GetString("ERR_AddNullControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command type specified. Use AddBaseCommand() instead..
        /// </summary>
        internal static string ERR_AddRenderCommand {
            get {
                return ResourceManager.GetString("ERR_AddRenderCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid update command specified. Use AddBaseCommand() or AddRenderCommand() instead.
        /// </summary>
        internal static string ERR_AddUpdateCommand {
            get {
                return ResourceManager.GetString("ERR_AddUpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} is not valid for method {1}.{2}. See the InnerException for details..
        /// </summary>
        internal static string ERR_Argument {
            get {
                return ResourceManager.GetString("ERR_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} for method {1}.{2} cannot be null..
        /// </summary>
        internal static string ERR_ArgumentNull {
            get {
                return ResourceManager.GetString("ERR_ArgumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} array does not hold {1} elements..
        /// </summary>
        internal static string ERR_ArrayElements {
            get {
                return ResourceManager.GetString("ERR_ArrayElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection already contains control: {0} .
        /// </summary>
        internal static string ERR_ControlInCollection {
            get {
                return ResourceManager.GetString("ERR_ControlInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot create a {0} object from a null {1} type..
        /// </summary>
        internal static string ERR_CreatingFromObject {
            get {
                return ResourceManager.GetString("ERR_CreatingFromObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Enum value not valid..
        /// </summary>
        internal static string ERR_EnumNotValid {
            get {
                return ResourceManager.GetString("ERR_EnumNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERR_Error {
            get {
                return ResourceManager.GetString("ERR_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Error..
        /// </summary>
        internal static string ERR_Fatal {
            get {
                return ResourceManager.GetString("ERR_Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is not yet supported in the Odyssey Engine..
        /// </summary>
        internal static string ERR_FeatureNotSupported {
            get {
                return ResourceManager.GetString("ERR_FeatureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Filename not valid..
        /// </summary>
        internal static string ERR_FilenameNotValid {
            get {
                return ResourceManager.GetString("ERR_FilenameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font cannot be null..
        /// </summary>
        internal static string ERR_FontCannotBeNull {
            get {
                return ResourceManager.GetString("ERR_FontCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least a RenderableNode child is required for a FreeTransformNode.
        /// </summary>
        internal static string ERR_FtNodeRequiresRNode {
            get {
                return ResourceManager.GetString("ERR_FtNodeRequiresRNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : Variable not found in effect file..
        /// </summary>
        internal static string ERR_FXVarNotFound {
            get {
                return ResourceManager.GetString("ERR_FXVarNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no vertices in the chosen HUD!.
        /// </summary>
        internal static string ERR_HudNoControls {
            get {
                return ResourceManager.GetString("ERR_HudNoControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection already contains a control by the same Id: {0}.
        /// </summary>
        internal static string ERR_IdInCollection {
            get {
                return ResourceManager.GetString("ERR_IdInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The control with the specified id was not found..
        /// </summary>
        internal static string ERR_IdNotFound {
            get {
                return ResourceManager.GetString("ERR_IdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of vertices specified for the specified Shape value..
        /// </summary>
        internal static string ERR_InvalidNumVertices {
            get {
                return ResourceManager.GetString("ERR_InvalidNumVertices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key not found in {0}: {1}.
        /// </summary>
        internal static string ERR_KeyNotFound {
            get {
                return ResourceManager.GetString("ERR_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized material parameter..
        /// </summary>
        internal static string ERR_MaterialParameter {
            get {
                return ResourceManager.GetString("ERR_MaterialParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file: {0} is missing..
        /// </summary>
        internal static string ERR_MissingFile {
            get {
                return ResourceManager.GetString("ERR_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ControlDescription file loaded. Be sure to call LoadControlDescription first..
        /// </summary>
        internal static string ERR_NoControlDescription {
            get {
                return ResourceManager.GetString("ERR_NoControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No details available..
        /// </summary>
        internal static string ERR_NoDetails {
            get {
                return ResourceManager.GetString("ERR_NoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TextDescription file loaded. Be sure to call LoadTextDescription first..
        /// </summary>
        internal static string ERR_NoTextDescription {
            get {
                return ResourceManager.GetString("ERR_NoTextDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your hardware device does not support shaders version 2.0!.
        /// </summary>
        internal static string ERR_ShaderModelNotSupported {
            get {
                return ResourceManager.GetString("ERR_ShaderModelNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This parameter is not applicable to spotlights..
        /// </summary>
        internal static string ERR_SpotlightParameter {
            get {
                return ResourceManager.GetString("ERR_SpotlightParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified style file was not found..
        /// </summary>
        internal static string ERR_StyleNotFound {
            get {
                return ResourceManager.GetString("ERR_StyleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target control must not be null..
        /// </summary>
        internal static string ERR_TargetControlNull {
            get {
                return ResourceManager.GetString("ERR_TargetControlNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The technique {1} was not found in {0} collection..
        /// </summary>
        internal static string ERR_TechniqueNotFound {
            get {
                return ResourceManager.GetString("ERR_TechniqueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This node can only be added to a TransformNode..
        /// </summary>
        internal static string ERR_TNodeRequired {
            get {
                return ResourceManager.GetString("ERR_TNodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized parameter..
        /// </summary>
        internal static string ERR_UnrecognizedParameter {
            get {
                return ResourceManager.GetString("ERR_UnrecognizedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is not  valid in {1}..
        /// </summary>
        internal static string ERR_WrongCase {
            get {
                return ResourceManager.GetString("ERR_WrongCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture not cached.
        /// </summary>
        internal static string RES_TextureNotCached {
            get {
                return ResourceManager.GetString("RES_TextureNotCached", resourceCulture);
            }
        }
    }
}
